kind: Template
apiVersion: v1
metadata:
  name: springboot-sti
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: springboot-sti
  spec:
    triggers:
    - type: GitHub
      github:
        secret: secret
    - type: Generic
      generic:
        secret: secret
    - type: ImageChange
      imageChange: {}
    source:
      type: Git
      git:
        uri: ssh://git@gitlab.consulting.redhat.com:2222/ncr/springboot-sti.git
        ref: master
      contextDir: spring-boot/springboot-sti
      sourceSecret:
        name: source-secret
    strategy:
      type: Docker
      dockerStrategy:
        noCache: true
        from:
          kind: DockerImage
          name: rhel7.2
    output:
      to:
        kind: ImageStreamTag
        name: springboot-sti:latest
    resources: {}
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: springboot-sti
  spec:
    dockerImageRepository: ''
    tags:
    - name: latest
      annotations:
        description: Spring Boot STI image
        iconClass: icon-jboss
        tags: builder,springboot,java,maven,gradle
        supports: springboot,java:8,maven:3,gradle:2.6
        version: '1.0'

